import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'


export default function Home() {


  const [pokemon, putPokemon]= useState( []);
  const [selectedpokemon,setpokemon] =useState(null);
  const [query,setQuery]=useState('');
  

  
  
useEffect(()=>{

  

},[]);






  return (
    <div >
      <Head>
        <title>Create Next Apbp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" ></link>
      </Head>

      <main >
        <div >

      <div id="search-box" style={{backgroundColor:"blue",height:"55px"}}>
			<div className="row m-0">
					<div className="col-sm-3 text-center p-3">
					</div>
					<div style={{marginLeft:"25px"}}>
							<form className="mb-0  d-flex justify-content-center align-items-center h-100 w-100" >
								<div>
									<input id="search_name" type="text" 
                  value={query}
                  onChange={(e)=>{
                    setQuery(e.currentTarget.value);
                    

                  }}
                  
                  placeholder="Enter Pokemon Name"/>
									<input id="submit_button" 
                  onClick={(e)=>{
                    e.preventDefault();
                    console.log("searched for "+query)
                    fetch(`https://pokeapi.co/api/v2/pokemon/${query}`)
                    .then((resp,Response)=>resp.json())
                    .then(data=>{

                      putPokemon(data);
                      console.log(data);


                    });


                    
                  }
                  }
                  type="submit" value="Search" className="btn btn-light p-2"/>
								</div>
							</form>
					</div>
			</div>
		</div>
</div>
        

        <h1>{pokemon?.name}</h1>
        



        {pokemon?.sprites && (
            <img src={pokemon.sprites.front_default} />
          )}

{pokemon.types?.length > 0 && (
          <ul>

            {pokemon.types.map((t)=>{
             
              return <li>{t.type.name}</li> 
              


            }
            
            )}

          </ul>
        )}
        <div>

          

          



        </div>

     

        

              </main>

      
    </div>
  )
}
