import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'


export default function Home() {


  const [pokemon, setPokemon]= useState( []);
  const [selectedpokemon,setpokemon] =useState(null);

  const fetchProcess=()=>{
  
    fetch('https://pokeapi.co/api/v2/pokemon')
    .then((resp,Response)=>resp.json())
    .then(data=>{
      console.log(data.results);
      setPokemon(data.results);
      
     
      
    });
   
  }
  
useEffect(()=>{

  fetchProcess();

},[]);

  




  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next Apbp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        

  
        {pokemon?.map((p)=>
        <div>
          <button onClick={() => setpokemon(p.name)}>{p.name}</button> 
        </div>
        
        )}
        <h1>Selected Pokemon:::{selectedpokemon}</h1>
              </main>

      
    </div>
  )
}
